# Generated by Django 3.0.4 on 2020-03-31 06:24

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200321_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(max_length=1000, null=True, verbose_name='사는 곳'),
        ),
        migrations.AddField(
            model_name='account',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='생년월일'),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profiles/', verbose_name='프로필 사진'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='4~150자의 문자, 숫자 그리고 @/./+/-/_만 가능합니다.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator(), django.core.validators.MinLengthValidator(4)], verbose_name='아이디'),
        ),
    ]
